@ecommerce_db_api_HostAddress = http://localhost:5234

GET {{ecommerce_db_api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET http://localhost:5234

###

GET http://localhost:5234/api/users

###

GET http://localhost:5234/api/users/91d6557d-4623-43e1-9a5a-4e2b480b4d05

###

DELETE http://localhost:5234/api/users/cb8966c9-8331-43f2-b441-96aa48c5b88e

###

POST http://localhost:5234/api/users 
Content-Type: application/json

{
  "userName" : "test5",
  "Email" : "test5@gmail.com",
  "Password" : "123456"
}

###

PUT http://localhost:5234/api/users/c2dc333b-0a31-4c20-80c4-ee3644201c17 
Content-Type: application/json

{
  "userName" : "alex"
}

###

GET http://localhost:5234/api/categories

###

POST http://localhost:5234/api/categories 
Content-Type: application/json

{
  "name": "Electronics",
  "description": "Devices and gadgets including phones, laptops, and other electronic equipment"
}

###

POST http://localhost:5234/api/products 
Content-Type: application/json

{
"name": "Mens Cotton Jacket 2",
"price": 55.99,
"description": "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
"image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
"quantity": 12,
  "shipping": 0,
  "categoryId": "84be1b97-1ef0-4012-9def-da973b2428e5"
}

###

GET http://localhost:5234/api/products 